[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.build]
cmds = [
  "pip3 install --upgrade pip3",
  "pip3 install -r backend/requirements.txt",
  "cd frontend && npm install --legacy-peer-deps && npm run build"
]

[phases.release]
cmds = [
  "cd backend && python3 manage.py collectstatic --noinput"
]

[start]
cmd = "cd backend && gunicorn uk_water_tracker.wsgi --bind 0.0.0.0:8000"
