# Generated by Django 4.2.7 on 2025-06-16 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScottishWaterResourceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.FloatField(help_text='Storage level as a percentage')),
                ('last_updated', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scottish water resource level',
                'verbose_name_plural': 'Scottish water resource levels',
            },
        ),
        migrations.CreateModel(
            name='WaterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('station_type', models.CharField(choices=[('river', 'River'), ('lake', 'Lake'), ('reservoir', 'Reservoir'), ('coastal', 'Coastal')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.FloatField(help_text='Water level in meters')),
                ('normal_level', models.FloatField(help_text='Normal water level in meters')),
                ('status', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('very_high', 'Very High')], max_length=20)),
                ('trend', models.CharField(choices=[('rising', 'Rising'), ('falling', 'Falling'), ('stable', 'Stable')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_levels', to='water_levels.waterstation')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_hour', models.FloatField(help_text='Predicted level in 1 hour')),
                ('next_6_hours', models.FloatField(help_text='Predicted level in 6 hours')),
                ('next_24_hours', models.FloatField(help_text='Predicted level in 24 hours')),
                ('confidence', models.IntegerField(help_text='Prediction confidence percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='water_levels.waterstation')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='water_levels.waterstation')),
            ],
        ),
    ]
