# Generated by Django 4.2.7 on 2025-08-12 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EAwaterStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScottishWaterAverageLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current', models.FloatField()),
                ('change_from_last_week', models.FloatField()),
                ('difference_from_average', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SevernTrentReservoirLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('percentage', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='YorkshireReservoirData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('reservoir_level', models.FloatField()),
                ('weekly_difference', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='YorkshireWaterPredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=10)),
                ('predicted_reservoir_percent', models.FloatField()),
                ('actual_reservoir_percent', models.FloatField(blank=True, null=True)),
                ('reservoir_error', models.FloatField(blank=True, null=True)),
                ('predicted_demand_mld', models.FloatField()),
                ('actual_demand_mld', models.FloatField(blank=True, null=True)),
                ('demand_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='YorkshireWaterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_reservoir_percent', models.FloatField()),
                ('predicted_demand_mld', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='SouthernWaterReservoirLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('current_level', models.FloatField()),
                ('average_level', models.FloatField()),
                ('change_week', models.FloatField()),
                ('change_month', models.FloatField()),
                ('difference_from_average', models.FloatField()),
            ],
            options={
                'ordering': ['reservoir', '-date'],
                'unique_together': {('reservoir', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SouthernWaterReservoirForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('predicted_level', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10)),
            ],
            options={
                'ordering': ['reservoir', 'date'],
                'unique_together': {('reservoir', 'date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='SouthernWaterForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservoir', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=10)),
                ('predicted_level', models.FloatField()),
                ('actual_level', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['reservoir', '-date'],
                'unique_together': {('reservoir', 'date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='SevernTrentReservoirForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_percentage', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='SevernTrentForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=10)),
                ('predicted_percentage', models.FloatField()),
                ('actual_percentage', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='ScottishWaterRegionalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('current', models.FloatField()),
                ('change_from_last_week', models.FloatField()),
                ('difference_from_average', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['area'],
                'unique_together': {('area', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScottishWaterRegionalForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('predicted_level', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10)),
            ],
            options={
                'ordering': ['area', 'date'],
                'unique_together': {('area', 'date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='ScottishWaterPredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=10)),
                ('predicted_value', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['area', '-date'],
                'unique_together': {('area', 'date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='ScottishWaterForecastAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=10)),
                ('predicted_percentage', models.FloatField()),
                ('actual_percentage', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='ScottishWaterForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_percentage', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
        migrations.CreateModel(
            name='EAwaterPredictionAccuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('model_type', models.CharField(max_length=20)),
                ('predicted_value', models.FloatField()),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('percentage_error', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('region', 'model_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EAwaterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('model_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('region', 'model_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='EAwaterLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
                ('quality', models.CharField(default='Unknown', max_length=50)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='water_levels.eawaterstation')),
            ],
            options={
                'unique_together': {('station', 'date')},
            },
        ),
    ]
