# Generated by Django 4.2.7 on 2025-08-12 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0001_initial'),
    ]    
        
    operations = [
        # 1) Turn OFF foreign key enforcement (SQLite only, no-op elsewhere)
        migrations.RunSQL("PRAGMA foreign_keys=OFF;"),

        # 2) Rebuild EAwaterLevel.station without a DB constraint.
        #    On SQLite this recreates the table and removes the stale FK
        migrations.AlterField(
            model_name="eawaterlevel",
            name="station",
            field=models.ForeignKey(
                to="water_levels.EAwaterStation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                db_constraint=False,
            ),
        ),

        # 3) Turn FK checks back ON
        migrations.RunSQL("PRAGMA foreign_keys=ON;"),
    ]
