# Generated by Django 4.2.7 on 2025-08-12 20:33

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0002_drop_ea_level_fk_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name="eawaterlevel",
            name="station",
            field=models.ForeignKey(
                to="water_levels.EAwaterStation",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="levels",
                db_constraint=True,
            ),
        ),
    ]
