# Generated by Django 4.2.7 on 2025-06-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0002_scottish_average_and_regional"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScottishWaterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("region", models.CharField(max_length=100)),
                ("current", models.CharField(max_length=20)),
                ("change_from_last_week", models.CharField(max_length=20)),
                ("diff_from_average", models.CharField(max_length=20)),
                ("source_url", models.URLField()),
            ],
            options={
                "ordering": ["-date", "region"],
                "unique_together": {("date", "region")},
            },
        ),
    ]
