# Generated by Django 4.2.7 on 2025-06-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "water_levels",
            "0004_remove_alert_station_remove_prediction_station_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="SevernTrentReservoirLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("percentage", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
