# Generated by Django 4.2.7 on 2025-06-17 15:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0005_severntrentreservoirlevel"),
    ]

    operations = [
        migrations.CreateModel(
            name="SevernTrentReservoirForecast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField()),
                ("predicted_percentage", models.FloatField()),
                (
                    "model_type",
                    models.CharField(
                        max_length=10,
                        choices=(
                            ("ARIMA", "ARIMA"),
                            ("LSTM", "LSTM"),
                        ),
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "model_type")},
            },
        ),
    ]

