# Generated by Django 4.2.7 on 2025-06-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0006_severntrentforecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='YorkshireWaterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_month', models.DateField(unique=True)),
                ('rainfall_percent_lta', models.FloatField()),
                ('reservoir_percent', models.FloatField()),
                ('reservoir_weekly_delta', models.FloatField()),
                ('river_condition', models.CharField(max_length=100)),
                ('demand_megalitres_per_day', models.FloatField()),
                ('source_pdf', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_month'],
            },
        ),
        migrations.CreateModel(
            name='YorkshireWaterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('predicted_reservoir_percent', models.FloatField()),
                ('predicted_demand_mld', models.FloatField()),
                ('model_type', models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM')], max_length=10)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('date', 'model_type')},
            },
        ),
    ]
