# Generated by Django 4.2.7 on 2025-06-18 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0007_yorkshirereservoirdata'),
        ('water_levels', '0007_yorkshirewaterreport_yorkshirewaterprediction'),
    ]

    operations = [
    ]
