# Generated by Django 4.2.7 on 2025-06-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0008_merge_20250618_1640"),
    ]

    operations = [
        migrations.CreateModel(
            name="SouthernWaterReservoirLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservoir", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("current_level", models.FloatField()),
                ("average_level", models.FloatField()),
                ("change_week", models.FloatField()),
                ("change_month", models.FloatField()),
                ("difference_from_average", models.FloatField()),
            ],
            options={
                "ordering": ["reservoir", "-date"],
                "unique_together": {("reservoir", "date")},
            },
        ),
        migrations.CreateModel(
            name="SouthernWaterReservoirForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reservoir", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("predicted_level", models.FloatField()),
                (
                    "model_type",
                    models.CharField(
                        choices=[("ARIMA", "ARIMA"), ("LSTM", "LSTM")], max_length=10
                    ),
                ),
            ],
            options={
                "ordering": ["reservoir", "date"],
                "unique_together": {("reservoir", "date", "model_type")},
            },
        ),
    ]
