# Generated by Django 4.2.7 on 2025-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0009_southernwaterreservoirlevel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='severntrentreservoirforecast',
            name='model_type',
            field=models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='southernwaterreservoirforecast',
            name='model_type',
            field=models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10),
        ),
        migrations.AlterField(
            model_name='yorkshirewaterprediction',
            name='model_type',
            field=models.CharField(choices=[('ARIMA', 'ARIMA'), ('LSTM', 'LSTM'), ('REGRESSION', 'REGRESSION')], max_length=10),
        ),
    ]
