# Generated by Django 4.2.7 on 2025-06-23 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0010_alter_severntrentreservoirforecast_model_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroundwaterStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("region", models.CharField(max_length=10)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GroundwaterLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                ("quality", models.CharField(default="Unknown", max_length=50)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="water_levels.groundwaterstation",
                    ),
                ),
            ],
            options={
                "unique_together": {("station", "date")},
            },
        ),
    ]
