# Generated by Django 4.2.7 on 2025-06-25
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0011_groundwaterstation_groundwaterlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroundwaterPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=10)),
                ('model_type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('predicted_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('region', 'model_type', 'date')},
            },
        ),
    ]
