# Generated by Django 4.2.7 on 2025-06-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0014_prediction_accuracy_extensions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scottishwaterpredictionaccuracy',
            options={'ordering': ['area', '-date']},
        ),
        migrations.AlterModelOptions(
            name='severntrentforecastaccuracy',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='southernwaterforecastaccuracy',
            options={'ordering': ['reservoir', '-date']},
        ),
        migrations.AlterModelOptions(
            name='yorkshirewaterpredictionaccuracy',
            options={'ordering': ['-date']},
        ),
    ]
