# Generated by Django 4.2.7 on 2025-06-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0015_alter_scottishwaterpredictionaccuracy_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScottishWaterForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("predicted_percentage", models.FloatField()),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("ARIMA", "ARIMA"),
                            ("LSTM", "LSTM"),
                            ("REGRESSION", "REGRESSION"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("date", "model_type")},
            },
        ),
    ]
