# Generated by Django 4.2.7 on 2025-07-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0017_scottishwaterregionalforecast'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroundwaterLevel',
            new_name='EnglandwaterLevel',
        ),
        migrations.RenameModel(
            old_name='GroundwaterPrediction',
            new_name='EnglandwaterPrediction',
        ),
        migrations.RenameModel(
            old_name='GroundwaterPredictionAccuracy',
            new_name='EnglandwaterPredictionAccuracy',
        ),
        migrations.RenameModel(
            old_name='GroundwaterStation',
            new_name='EnglandwaterStation',
        ),
    ]
