# Generated by Django 4.2.7 on 2025-07-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("water_levels", "0018_rename_groundwaterlevel_EAwaterlevel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScottishWaterForecastAccuracy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("model_type", models.CharField(max_length=10)),
                ("predicted_percentage", models.FloatField()),
                ("actual_percentage", models.FloatField(blank=True, null=True)),
                ("percentage_error", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("date", "model_type")},
            },
        ),
    ]
