# Generated by Django 4.2.7 on 2025-07-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0019_scottishwaterforecastaccuracy'),
    ]

    operations = [
        migrations.AddField(
            model_name='southernwaterforecastaccuracy',
            name='forecast_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
