# Generated by Django 4.2.7 on 2025-08-12 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water_levels', '0020_southernwaterforecastaccuracy_forecast_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YorkshireWaterReport',
        ),
    ]
