# Generated by Django 4.2 on 2025-06-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IssueReport",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("issue_type", models.CharField(max_length=50)),
                ("severity", models.CharField(max_length=20)),
                ("location", models.CharField(max_length=255)),
                ("postcode", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("contact_name", models.CharField(blank=True, max_length=255)),
                ("contact_phone", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
