# Generated by Django 4.2 on 2025-06-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0002_issue_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="supportrequest",
            name="phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="urgent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="supportrequest",
            name="newsletter",
            field=models.BooleanField(default=False),
        ),
    ]
