# Generated by Django 4.2.7 on 2025-06-15 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('Alert', 'Alert'), ('Update', 'Update'), ('Technology', 'Technology'), ('Research', 'Research'), ('Infrastructure', 'Infrastructure'), ('Water Level', 'Water Level'), ('Water Quality', 'Water Quality'), ('Storm', 'Storm')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('tags', models.JSONField(default=list)),
                ('urgent', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
