# Generated by Django 4.2.7 on 2025-06-10 18:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('condition', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('precipitation', models.IntegerField(help_text='Precipitation probability percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_forecasts', to='weather.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='DailyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('high_temp', models.FloatField(help_text='High temperature in Celsius')),
                ('low_temp', models.FloatField(help_text='Low temperature in Celsius')),
                ('condition', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('precipitation', models.IntegerField(help_text='Precipitation probability percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_forecasts', to='weather.weatherstation')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('feels_like', models.FloatField(help_text='Feels like temperature in Celsius')),
                ('condition', models.CharField(max_length=100)),
                ('icon', models.CharField(max_length=50)),
                ('humidity', models.IntegerField(help_text='Humidity percentage')),
                ('wind_speed', models.FloatField(help_text='Wind speed in mph')),
                ('wind_direction', models.CharField(max_length=10)),
                ('pressure', models.IntegerField(help_text='Pressure in mb')),
                ('visibility', models.FloatField(help_text='Visibility in km')),
                ('uv_index', models.IntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_weather', to='weather.weatherstation')),
            ],
        ),
    ]
