# Generated by Django 4.2.7 on 2025-06-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyforecast',
            name='cloud_cover_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='cloud_cover_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='cloud_cover_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='humidity_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='humidity_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='humidity_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='precipitation_probability_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='precipitation_probability_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='precipitation_probability_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='sunrise_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='sunset_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='temperature_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='temperature_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='temperature_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='weather_code_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='weather_code_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='wind_speed_avg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='wind_speed_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyforecast',
            name='wind_speed_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='cloud_cover',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='dew_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='freezing_rain_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='precipitation_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='pressure_sea_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='rain_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='sleet_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='snow_intensity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='temperature_apparent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='uv_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='visibility',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='weather_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='wind_direction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='wind_gust',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hourlyforecast',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='high_temp',
            field=models.FloatField(blank=True, help_text='High temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='low_temp',
            field=models.FloatField(blank=True, help_text='Low temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='dailyforecast',
            name='precipitation',
            field=models.IntegerField(blank=True, help_text='Precipitation probability percentage', null=True),
        ),
        migrations.AlterField(
            model_name='hourlyforecast',
            name='condition',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='hourlyforecast',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='hourlyforecast',
            name='precipitation',
            field=models.IntegerField(blank=True, help_text='Precipitation probability percentage', null=True),
        ),
        migrations.AlterField(
            model_name='hourlyforecast',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
    ]
