# Generated by Django 4.2.7 on 2025-06-12 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_dailyforecast_cloud_cover_avg_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailyforecast',
            unique_together={('station', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='hourlyforecast',
            unique_together={('station', 'time')},
        ),
    ]
