# Generated by Django 4.2.7 on 2025-06-23 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_alter_dailyforecast_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherstation',
            options={'ordering': ['name']},
        ),
    ]
